# Generated by Django 2.2.2 on 2019-06-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='注册时间'),
        ),
    ]
