# Generated by Django 2.2.2 on 2019-07-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190621_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gain_votes',
            field=models.IntegerField(default=0, verbose_name='得票数'),
        ),
    ]
