# Generated by Django 2.2.2 on 2019-07-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_brithday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='brithday',
            new_name='birthday',
        ),
    ]
