# Generated by Django 2.2.2 on 2019-07-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190730_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_unread_notice',
            field=models.BooleanField(default=False, verbose_name='该用户有未读消息'),
        ),
    ]
