# Generated by Django 2.2.2 on 2019-07-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='visited_num',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
