# Generated by Django 2.2.2 on 2019-07-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_question_visited_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '问题', 'verbose_name_plural': '问题'},
        ),
    ]
