# Generated by Django 2.2.2 on 2019-06-25 05:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circlemessage',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否已经删除'),
        ),
        migrations.AlterField(
            model_name='circlemessage',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a7804cda-2b96-4c71-be25-5b9465ba8900'), editable=False, unique=True),
        ),
    ]
