# Generated by Django 2.2.2 on 2019-06-28 09:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_auto_20190625_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circlemessage',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a0909232-2e68-4bd2-8344-f8a43b269a79'), editable=False, unique=True),
        ),
    ]
