# Generated by Django 2.2.2 on 2019-07-06 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0003_auto_20190628_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circlemessage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
