# Generated by Django 2.2.2 on 2019-07-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0004_auto_20190706_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circlemessage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
    ]
