# Generated by Django 2.2.2 on 2019-07-03 05:49

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='types',
            field=models.CharField(choices=[('yc', '原创'), ('fy', '翻译'), ('zz', '转载')], max_length=255, null=True, verbose_name='文章类型'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='article/%Y/%m/%d/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('1', '发布'), ('0', '草稿')], default=0, max_length=1, verbose_name='文章状态'),
        ),
    ]
