# Generated by Django 2.2.2 on 2019-07-22 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.UUID('06a6cae8-d621-4252-af46-e249b4a1244b'), editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='是否已读')),
                ('verb', models.CharField(choices=[('L', '赞了'), ('C', '评论了'), ('F', '收藏了'), ('A', '回答了'), ('W', '接受了回答'), ('R', '回复了')], max_length=1, verbose_name='通知类别')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n_recipient_user', to=settings.AUTH_USER_MODEL, verbose_name='消息接受者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n_sender_user', to=settings.AUTH_USER_MODEL, verbose_name='消息发送者')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
            },
        ),
    ]
