# Generated by Django 2.2.2 on 2019-07-30 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ('-create_time',), 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AlterField(
            model_name='notice',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='verb',
            field=models.CharField(choices=[('L', '赞了'), ('A', '回答了'), ('W', '采纳了'), ('R', '回复了'), ('V', '投票了')], max_length=1, verbose_name='通知类别'),
        ),
    ]
